version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

#  web:
#    build: .
#    container_name: fastapi-app
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db

volumes:
  db_data:
